
remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: mySite4Test # 增加title 否则报错
description: 测试 Primer theme # 增加 description 否则报错
repository: georgedonnev2/log

# 新增：指定构建输出目录
destination: ./docs
# baseurl: "/log"
# url: "https://georgedonnev2.github.io"

# 构建配置
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false