version: '3'
services:
  jekyll:
    image: jekyll/jekyll:latest
    ports:
      - "4000:4000"
    volumes:
      - ~/gdweb/log:/srv/jekyll
    command: jekyll serve --host 0.0.0.0 --watch --force_polling