# version: '3'
services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: mylog  # 容器名称
    ports:
      - "4000:4000"
    volumes:
      - ~/gdweb/log:/srv/jekyll
    environment:
      # 新增：设置 GitHub Pages 环境
      JEKYLL_ENV: production
      PAGES_REPO_NWO: "georgedonnev2/log"
    # command: jekyll serve --host 0.0.0.0 --watch --force_polling
    command: >
      sh -c "
      cd /srv/jekyll &&
      jekyll build --destination ./docs &&
      jekyll serve --host 0.0.0.0 --watch --force_polling
      "